### ISSUE TITLE
Launcher Error Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.

### ISSUE THREAD

**Issue by frohro** [jupyterlab/jupyterlab-desktop#240]
I cannot launch either octave or python kernels.  I get this error:
Launcher Error
Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.

![image](https://user-images.githubusercontent.com/994565/134615451-086f469c-5196-4e7c-9057-a8da36f871eb.png)

To reproduce it, just install JupyterLab_app on Ubuntu 21.04 and start it.  Then click the Python 3 launcher.

\

## Context
This is on Ubuntu 21.04.  I have an ordinary jupyter-lab that uses the browser installed too, and it works fine.  I used the .deb to install it just now.

\

**Comment by krassowski** [comment]
Could you please go to "Settings" -> "Advanced Settings Editor" -> "Notebook" and take a screenshot of the settings in both panels, in particular `observedBottomMargin` and `observedTopMargin`?

**Comment by frohro** [comment]
Hi Michal,
I'd be glad to, but I can't find the menu, much less the Settings menu.  Here is what it looks like to me:
![image](https://user-images.githubusercontent.com/994565/134728161-94814e07-038f-4bda-9d43-f4f347cf3235.png)
Any help?
Thanks,
Rob

**Comment by krassowski** [comment]
That's weird. My guess is that you may have had a different version of JupyterLab installed and its settings are overwriting the jupyterlab-app settings; this would explain missing menu bar. To open `Advanced Settings Editor` directly you can use <kbd>Ctrl</kbd> + <kbd>,</kbd>, but with the new bit of information about missing menu I am quite confident the issue is in the settings files being overwritten.

If you had installed an older version of JupyterLab previously, could you please run `jupyter --path` from the environment it was installed in and iterate through the `config` paths, checking if there is a `lab/user-settings/@jupyterlab/` directory and trying to rename it temporarily and then restart/reinstall jupyterlab-app?

If you are using Ubuntu I would guess it might be in `~/.jupyter`

**Comment by krassowski** [comment]
CC @fcollonval and @echarles as FYI that maybe the transition from older versions could be disrupted by the recent changes in notebook settings and setting-based menus without defaults to fallback to (not requesting any action, just letting you know in case if you noticed this earlier or have ideas to solve this).

**Comment by frohro** [comment]
Yes, it is in ~/.jupyter as this shows:
frohro@frohro-A475:~$ jupyter --path
config:
    /home/frohro/.jupyter
    /usr/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/frohro/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/frohro/.local/share/jupyter/runtime
I moved .jupyter to .jupyter_old and restarted JupyterLab_app, but no menu appeared.  Then I removed it including configuration files using Synaptic,  then I did $ sudo apt install ./JupyterLab-Setup-Debian.deb in the terminal.  I'm still seeing this?  Did I miss something?  Do I need to remove the stuff in /etc too?
![image](https://user-images.githubusercontent.com/994565/134740754-bb53727e-c9b3-4031-ab8a-e434f81e252c.png)

Thanks,
Rob

**Comment by frohro** [comment]
I am able to start the settings with CTRL+, but I cannot find the Advanced Settings Editor.  There is a "Notebook" section, but it doesn't have the parameters I was looking for.
Rob

**Comment by krassowski** [comment]
Thank you! This is exactly the `Advanced Settings Editor` (just labelled as `Settings` here). This is very useful, indeed there is no "Main Menu" tab, nor the `observedBottomMargin`/`observedTopMargin`; this is how it looks like for me:

![Screenshot from 2021-09-24 22-29-49](https://user-images.githubusercontent.com/5832902/134741788-cccf11cb-cbab-49c9-8bf0-b73fe99a3a8e.png)

**Comment by krassowski** [comment]
Could it be that one of the other paths shown in your `config` section (after running `jupyter --path`) contains another copy of the `lab/user-settings/@jupyterlab/`?

**Comment by krassowski** [comment]
Looking more at your screenshot, there is something else that is wrong. The CSS styles seem to correspond to older JupyterLab version (light blue instead of dark blur on selections) and the tooltip displayed after hovering on the Code Console visible on your screenshot shows that it uses 3.0.10 version - this is odd. I am out of ideas, maybe @mbektas could weigh in with some more knowledge.

**Comment by krassowski** [comment]
Okay, one more: is your "ordinary" JupyterLab installation global (on system level rather than contained to a virtual environment)? Could you try uninstalling it and see if this gets fixed?

**Comment by frohro** [comment]
Uninstalling jupyterlab using pip uninstall jupyterlab seems to have worked!  I guess I have to decide which I'm going to use.  I'll leave it with the JupyterLab_app for a while.  I'm not using it that much this quarter, so it may not get tested fully, but at least now I have a menu.  :-)
![image](https://user-images.githubusercontent.com/994565/134745480-1c9ac807-234e-46d3-add8-7ffa105b67cc.png)
Thanks!
Rob

**Comment by frohro** [comment]
I can also launch a kernel and do some python now!

**Comment by krassowski** [comment]
Hooray!

> Uninstalling jupyterlab using pip uninstall jupyterlab seems to have worked! I guess I have to decide which I'm going to use.

Possibly you could have both, but I would just ensure that the versions are the same.

**Comment by frohro** [comment]
I did a pip install --upgrade jupyterlab and now both versions seem to work.
Thanks!
Rob
