### ISSUE TITLE
Installation problems under Win10 or Ubuntu 20.10 ("Jupyter server not found")

### ISSUE THREAD

**Issue by chipmuenk** [jupyterlab/jupyterlab-desktop#321]
When trying to install the app (version 3.2.1-1) via the installers downloaded from this repo, I hit the following problems:

- Win10: When I have to select the installation path, "Next" is greyed out without explanation. Probably the environment variable %HOMEDRIVE% is not set correctly on my PC but shouldn't this be detected by the installer? Suggesting a different location? Changing the path manually worked though.
- Win10: The pop-up window displaying installation options mangles the text
- Win10 and Linux: After finishing installation, I receive the message "Jupyter Server Not Found" and that's it.

I am a long-time python user running jupyterlab from a regular python installation so I don't need the desktop app. But when looking for a solution for python / jupyter newbies shouldn't the process be as streamlined as possible? Shouldn't it be easier than doing a plain vanilla python + jupyter installation (which it isn't)?

I've been trying several solutions over the last 6 years to use Jupyter Notebooks in BYOD classroom environments, using web servers, JupyterHub, local installations and now the Jupyterlab Desktop App. Deployment has been a major PITA for all sorts of reasons every time. I thought one of the ideas behind Jupyter Notebooks was to provide an easy access to experimenting with data and code. Well, it isn't, looking at the feedback from my students every term.

![jupyterlab_win10](https://user-images.githubusercontent.com/4620020/139576674-ff005e1e-3875-462b-b1f3-9258c7f984b8.png)
![jupyterlab_win10_options](https://user-images.githubusercontent.com/4620020/139576679-913ee950-be72-4451-94c8-801c81bae792.png)
![jupyterlab_win10_server_not_found](https://user-images.githubusercontent.com/4620020/139576682-35215ef7-6c32-4ca0-ac47-0ef88e75679d.png)
.

**Comment by krassowski** [comment]
I suspect that this might be because there are two installers and they need to be provided paths in sync.

You mention that you needed to change the path in the first installer. What path did you set? Did you adjust the path of the second installer accordingly? Please see https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#windows-instructions. I of course think that there should be only one installer.

> Deployment has been a major PITA for all sorts of reasons every time. I thought one of the ideas behind Jupyter Notebooks was to provide an easy access to experimenting with data and code. Well, it isn't, looking at the feedback from my students every term.

I'm sorry for your experience. I understand it fully. I really want to make literate programming more accessible to every student and researcher (which is why I'm writing this response on Sunday morning). You may be interested in checking out server-less and installation-less [JupyterLite](https://github.com/jupyterlite/jupyterlite) which should eliminate the installation issues you mention.

Please bear in mind that the Desktop app was only recently revived and is improving by great strides every week. I apologize that communication on the readiness of the app was not clear.

**Comment by chipmuenk** [comment]
Thanks for your quick and detailled response and most of all for your contributions to the python and jupyter community. I usually don't rant on FOSS channels because I know how unrewarding FOSS development can be at times. After GESIS announced pulling the plug on their free notebook server service I was really frustrated to see that JupyterLab Desktop also doesn't work for me, meaning I have to find another way to deploy my DSP labs (or rewrite them) within three weeks.

Your response highlights one of the main problems in my eyes: There are two installers but this is not obvious for a "normal" user (who doesn't read instructions). Even for me, it is not clear what I did wrong during the installation process - there are no instructions or hints, it just fails. I had to change the installation path on windows as described - and I have absolutely no idea how or where I could have adjusted the path of the second installer. The instructions didn't really help me. On Linux I just went the default path but both installations failed exactly the same way.

Honestly, I think it is easier (and much better documented) to install python and jupyter(lab) via the usual channels and that's what I'll recommend to my students. I'm using Notebooks only for a quite narrow field (digital signal processing 101) so I think I'll fully switch to my own app next term which is more of the point and click type. But please do streamline the installation process.

Thanks also for pointing me to JupyterLite, I'll test it although I don't see the advantage yet over a simple `pip install jupyterlab`.

I'll leave this issue open, please close it yourself if you like.

**Comment by krassowski** [comment]
Thank you for the extra details. Two questions:
1. on Windows, have you tried installing as an administrator and selecting "install for All users"?
2. on Ubuntu, how did you install it? Did you use the GUI software manager, `gdebi`, `dpkg`, or `apt`?

**Comment by krassowski** [comment]
Would you mind posting the answers to the above questions in #238, please? It will help us to consolidate discussion and figure out what works across a variety of setups users may have and inform how to remediate the problem. I will close this one in the meantime.

PS. I did try on another laptop with Ubuntu 20.10 just a moment ago and it worked well, so really having more information would be really help.

**Comment by krassowski** [comment]
Thanks for posting extra information in the other issue. I will close this one as a duplicate and follow up on the other one. We worked to investigate and fix this problem in https://github.com/jupyterlab/jupyterlab-desktop/pull/339 and this will be included in the upcoming release. While it might not solve the issue, we at least hope that we might get the information necessary to find a solution (since the updated error screen should now show the underlying error).
