### ISSUE TITLE
Why dypes are different from the python script?

### ISSUE THREAD

**Issue by yucsong** [jupyterlab/jupyterlab-desktop#481]
Just a weird phenomenon:  when I output the pandas DataFrames using to_csv, they types are fine with Jupyterlab, but if I convert the script into a py file and use the same python to run it, the types are all changed to characters. 

What could be wrong???

**Comment by krassowski** [comment]
You might have be using different Python environments when in JupyterLab and when executing the script, which might lead to  different `pandas` versions being used.

It is unlikely to be a JupyterLab issue, but if you believe otherwise please re-open providing a reproducible example and filling out the bug report template.
