### ISSUE TITLE
Unable to use Jupyterlab Desktop with Alternative Python Installation

### ISSUE THREAD

**Issue by Imoh-mfon** [jupyterlab/jupyterlab-desktop#572]
Request help on how to use Jupyterlab desktop v3.6.1-1 with Python10.5 and 3.11.1. I am using a Windows 10 laptop and have tried the direction in the installation guide without any success to get the app..

**Comment by linonetwo** [comment]
Does Jupyterlab Desktop bundle a python binary with it? So user don't need to install python.

**Comment by mbektas** [comment]
@Imoh-mfon you can follow the instructions [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#how-to-create-a-custom-python-environment) to create a conda environment on your computer. After creating the environment, make sure to restart JupyterLab Desktop. If it was installed in common locations, the environment will be discovered otherwise you can select the environment (the path to python.exe in the environment directory) from the UI.

If you followed these steps, please share the error message you are receiving.

@linonetwo yes, JupyterLab Desktop bundles a Python environment and users are recommended to start with that environment.

**Comment by Imoh-mfon** [comment]
Dear Mehmet, 
Thank you so much for your time your guidance. It worked! 

Many thanks,
Mark Idiong. 
 
  On Mon, Feb 13, 2023 at 4:39, Mehmet ***@***.***> wrote:   


@Imoh-mfon you can follow the instructions here to create a conda environment on your computer. After creating the environment, make sure to restart JupyterLab Desktop. If it was installed in common locations, the environment will be discovered otherwise you can select the environment (the path to python.exe in the environment directory) from the UI.

If you followed these steps, please share the error message you are receiving.

@linonetwo yes, JupyterLab Desktop bundles a Python environment and users are recommended to start with that environment.
