### ISSUE TITLE
App Won't Start After Installing Python

### ISSUE THREAD

**Issue by AlexMorello** [jupyterlab/jupyterlab-desktop#739]
Upon restart (after using the built-in Python installer), the app icon in Dock jumps for a while, but the app never starts. Automatic updates were turned off in Settings before using the installer. macOS Mojave.

**Comment by JasonWeill** [comment]
@AlexMorello Which version of JupyterLab Desktop are you running? Notably, [version 4.0.7-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v4.0.7-1) removes support for macOS 10.14 (Mojave) and now requires macOS 10.15 (Catalina) or later, due to Electron removing support for older versions.
