### ISSUE TITLE
shortcut for toggling left activity bar avoids setting brackets and other important keyboard chars on macos

### ISSUE THREAD

**Issue by ArtMattner** [jupyterlab/jupyterlab-desktop#768]
## Description

By default the shortcuts to toggle the left activity bar are set to option key with numbers 1 to 0.
I can't change it and it avoids me to set brackets and other important chars on the keyboard.
Every time you want to open/close brackets you don't open or close them but instead this left activity bar toggles.

## Reproduce

1. Create a new Notebook or open an existing
2. Write some code and try to set a bracket with option + 5
3. See toggling the left activity bar

## Expected behavior

By keyboard "option + 5" I expect to get an opening square bracket: "["

## Context

- Operating System and version: MacOS Sonoma 14.3.1 
- JupyterLab-Desktop version: 14.1.0-1
![image](https://github.com/jupyterlab/jupyterlab-desktop/assets/155767753/6f3a4bce-ddf3-49b8-8891-0f4b946cbf38)

**Comment by krassowski** [comment]
@ArtMattner thank you for reporting. This is tracked in https://github.com/jupyterlab/jupyterlab/issues/15744 and the part with Alt + key is already fixed, to be released later today. There is also an issue with backticks/square brackets on Italian (and possibly other) keyboard(s) which has a draft PR opened but requires user testing because unfortunately I do not have an Italian Mac available - please see: https://github.com/jupyterlab/jupyterlab/issues/15744#issuecomment-1938847894

**Comment by JasonWeill** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/15744. @ArtMattner Thank you for reporting this!

**Comment by ArtMattner** [comment]
I have to thank you for your fast and friendly investigation! @JasonWeill & @krassowski 👏
