### ISSUE TITLE
Bug: default install directory result in import error

### ISSUE THREAD

**Issue by yetong2023** [jupyterlab/jupyterlab-desktop#807]
To reproduce this:
`
!pip install paddlepaddle
import paddle

WinError 123 The name of the file or directory name tag syntax is incorrect：'\\\\?\\C:\\Users\\yt\\AppData\\Roaming\\jupyterlab-desktop\\jlab_server\\Lib\\site-packages\\paddle\\base\\..\\libs'`

While in other platform, such as anoconda jupyterlab, winpython jupyterlab, there is no such error.

**Comment by JasonWeill** [comment]
@yetong2023 Thanks for opening this issue! Which version of JupyterLab Desktop are you using and which Windows version are you using?

**Comment by mbektas** [comment]
I have been debugging this issue together with https://github.com/jupyterlab/jupyterlab-desktop/issues/784 and they both have the same root cause. When bundled environment is installed on Windows, the environment prefix has UNC path format, starting with `\\?\`. Python (or some libraries) are not able to resolve those paths causing these errors.

@yetong2023 as a workaround you can create a new Python environment (using [New environment](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/media/manage-envs-create-from-registry.png) option) and install the dependency there.

**Comment by JasonWeill** [comment]
@yetong2023 Any update regarding the most recent comment from @mbektas ?
