### ISSUE TITLE
I'm using arm64 linux, how do I install it?

### ISSUE THREAD

**Issue by liuxing-GitHub-lx** [jupyterlab/jupyterlab-desktop#858]
I'm using arm64 linux, how do I install it? I am using the Galaxy Kirin system, based on Ubuntu, the architecture of the CPU is arm64, I am a beginner in programming, how do I want to use the program?

**Comment by JasonWeill** [comment]
@liuxing-GitHub-lx Thanks for opening this issue! I don't see arm64 Linux binaries mentioned on this project's home page. You may be able to build JupyterLab Desktop from source to use it locally. Alternatively, you could try installing JupyterLab (rather than JupyterLab Desktop) either from your package manager of choice or by building from source. See the Contributor documentation for info about the latter: https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#setting-up-a-local-development-environment
